### ISSUE TITLE
Port to TM4c129x

### ISSUE THREAD

**Issue by PAk-CatchFire** [Lauszus/LaunchPadFlightController#11]
Hello, 
first of all....excellent work.

Will you port it to latest TM4c129x Tivaware family?
Regards.

**Comment by Lauszus** [comment]
Thanks :)
No I am not currently planning on it, but if you want to you are more than welcome to do so.

**Comment by PAk-CatchFire** [comment]
Thanks @Lauszus. Finally I was able to port it for 129X and 123X devices. But unfortunatelly, the yaw, raw and theta I am getting are not correct.

Would you mind to take a look on it? All the code is on my Github

https://github.com/PAk-CatchFire/MPU9250-Tivaware

Regards

**Comment by Lauszus** [comment]
@PAk-CatchFire what exactly do you want me to look at? If you want to use the driver for the MPU-9250, then you can just use mine. But you will have to change the I2C driver for the TM4C129x family: https://github.com/Lauszus/LaunchPadFlightController/blob/master/src/I2C.c.

**Comment by Lauszus** [comment]
Btw the TM4c129x family is not the "latest family", but simply a different family, which purpose is to use it for IoT etc.

**Comment by PAk-CatchFire** [comment]
Ok, the129x  I2C driver is one part I already implemented.

In which file is located your MPU-9250 driver? Is it spreaded through some files?

Thanks

**Comment by Lauszus** [comment]
As the MPU-9250 is the same sensor as the MPU-6500, but just with a AK8963 magnetometer inside. I simply use the MPU-6500 driver: https://github.com/Lauszus/LaunchPadFlightController/blob/master/src/MPU6500.c and then a dedicated driver for the magnetometer: https://github.com/Lauszus/LaunchPadFlightController/blob/master/src/AK8963.c.

Here is the commit that added support for the MPU-9250: https://github.com/Lauszus/LaunchPadFlightController/commit/527d39360ec56c56bb9e7cf42679e29b8ef919eb.

You shouldn't have to modify the driver in any way, as I use the TivaWare librayr: https://github.com/Lauszus/LaunchPadFlightController/tree/master/lib. The part is then simply set in the Makefile: https://github.com/Lauszus/LaunchPadFlightController/blob/master/src/Makefile#L28.

You might want to use different pins for the I2C interface: https://github.com/Lauszus/LaunchPadFlightController/blob/master/src/I2C.c, that is all you might have to change.

**Comment by PAk-CatchFire** [comment]
Thank you Lauszus, I was checking your drivers and they work fine for the accelerometer & gyro part, however the magnetometer gets stuck reading 0 values. So i used the function in my code:
https://github.com/PAk-CatchFire/MPU9250-Tivaware/blob/master/PAk_MPU9250_Tivaware/MPU9250/MPU9250.c#L472

I have improved my readings because I had some error on the scale, however my result is jittering (probably the filter is not good enough).

I haven't seen that you use any of the traditional Madgwick/Mahony QuaternionUpdate....are you using your own? Is it worth it?

Best Regards

**Comment by Lauszus** [comment]
I am just using a complimentary filter: https://github.com/Lauszus/LaunchPadFlightController/blob/master/src/IMU.c.
