### ISSUE TITLE
buzzer.c

### ISSUE THREAD

**Issue by mtayyip** [Lauszus/LaunchPadFlightController#15]
Hi,
in the buzzer code : 
GPIOPinTypeGPIOOutput(GPIO_BUZZER_BASE, GPIO_PIN_BUZZER);
it's running all the time buzzer.

And this code:
GPIOPinWrite(GPIO_BUZZER_BASE, GPIO_PIN_BUZZER, enable ? GPIO_PIN_BUZZER : 0);//enable is false
continues to work, does not stop

**Comment by moisesesc** [comment]
Could be the hardware... Shorted buzzer driver

On Feb 4, 2018 8:07 AM, Muhammet Tayyip Çankaya <notifications@github.com> wrote:

Hi,
in the buzzer code :
GPIOPinTypeGPIOOutput(GPIO_BUZZER_BASE, GPIO_PIN_BUZZER);
it's running all the time buzzer.

And this code:
GPIOPinWrite(GPIO_BUZZER_BASE, GPIO_PIN_BUZZER, enable ? GPIO_PIN_BUZZER : 0);//enable is false
continues to work, does not stop

**Comment by mtayyip** [comment]
I connected the vcc to 3.3 volts.now it is OK

**Comment by Lauszus** [comment]
@mtayyip good to hear you got it working :)
