### ISSUE TITLE
What's the LED status means?

### ISSUE THREAD

**Issue by MrThanlon** [Lauszus/LaunchPadFlightController#16]
- green?
- red?

**Comment by Lauszus** [comment]
The RED LED indicates that the flight controller is armed and the green indicates that it is unarmed. The blue LED has different meanings, please read the README for more information: https://github.com/Lauszus/LaunchPadFlightController#launchpad-flight-controller.

**Comment by Lauszus** [comment]
I'm closing this issue, as I believe it is solved. Please reopen if needed :)
